In [ ]:
import numpy as np

In [ ]:
aravali = np.array(np.random.randint(10, 40, (8,2)))
print(f"The defined array is \n{aravali}")
print(f"The shape of the array is {aravali.shape}")

The defined array is 
[[29 11]
 [21 34]
 [16 34]
 [28 17]
 [20 19]
 [35 34]
 [18 18]
 [39 31]]
The shape of the array is (8, 2)


In [ ]:
nilgiri = np.transpose(aravali)
print(f"The transposed array is \n {nilgiri}")
print(f"The shape of transposed array is {nilgiri.shape}")

The transposed array is 
 [[29 21 16 28 20 35 18 39]
 [11 34 34 17 19 34 18 31]]
The shape of transposed array is (2, 8)


In [ ]:
new_3d_array = np.array(np.random.randint(5,50,(3,5,2)))
print(new_3d_array)
print(f"The shape of array is {new_3d_array.shape}")

[[[18 27]
  [39 22]
  [28 24]
  [ 7 46]
  [16 37]]

 [[12  5]
  [12 35]
  [ 9 46]
  [36 18]
  [ 8 34]]

 [[35 36]
  [25 10]
  [ 5 12]
  [ 8  5]
  [17 33]]]
The shape of array is (3, 5, 2)


In [ ]:
transposed_array = np.transpose(new_3d_array)
print(transposed_array)
print(f"The shape of the array is {transposed_array.shape}")

[[[18 12 35]
  [39 12 25]
  [28  9  5]
  [ 7 36  8]
  [16  8 17]]

 [[27  5 36]
  [22 35 10]
  [24 46 12]
  [46 18  5]
  [37 34 33]]]
The shape of the array is (2, 5, 3)


In [ ]:
#New 2d array
array_2d = np.array(np.random.randint(1,10,(2,10)))
print(array_2d)
print(array_2d.shape)

[[9 1 8 5 1 4 6 4 1 2]
 [8 6 5 2 3 9 1 3 1 3]]
(2, 10)


In [ ]:
new_shape = (2,5,2)
reshaped_array = np.reshape(array_2d, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[9 1]
  [8 5]
  [1 4]
  [6 4]
  [1 2]]

 [[8 6]
  [5 2]
  [3 9]
  [1 3]
  [1 3]]]
(2, 5, 2)


In [ ]:
new_shape = (5,2,2)
reshaped_array = np.reshape(array_2d, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[9 1]
  [8 5]]

 [[1 4]
  [6 4]]

 [[1 2]
  [8 6]]

 [[5 2]
  [3 9]]

 [[1 3]
  [1 3]]]
(5, 2, 2)


In [ ]:
random_3d_array = np.array(np.random.randint(1,20,(2,4,2)))
print(random_3d_array)
print(random_3d_array.shape)

[[[ 6  1]
  [ 2  1]
  [ 7  2]
  [17 16]]

 [[ 4 17]
  [15  5]
  [12  4]
  [ 7  1]]]
(2, 4, 2)


In [ ]:
new_shape = (4,1,4)
reshaped_array = np.reshape(random_3d_array, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[ 6  1  2  1]]

 [[ 7  2 17 16]]

 [[ 4 17 15  5]]

 [[12  4  7  1]]]
(4, 1, 4)


In [ ]:
new_shape = (4,1,8)
reshaped_array = np.resize(random_3d_array, new_shape)
print(reshaped_array)
print(reshaped_array.shape)

[[[ 6  1  2  1  7  2 17 16]]

 [[ 4 17 15  5 12  4  7  1]]

 [[ 6  1  2  1  7  2 17 16]]

 [[ 4 17 15  5 12  4  7  1]]]
(4, 1, 8)


In [ ]:
random_3d_array.resize(new_shape)

In [ ]:
print(random_3d_array)

[[[ 6  1  2  1  7  2 17 16]]

 [[ 4 17 15  5 12  4  7  1]]

 [[ 0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0]]]


In [ ]:
random_3d_array = np.array(np.random.randint(1,10,(2,3,4)))
print(random_3d_array)
print(random_3d_array.shape)

[[[8 4 6 1]
  [1 3 6 7]
  [8 5 2 6]]

 [[7 2 4 8]
  [4 7 7 7]
  [9 6 6 3]]]
(2, 3, 4)


In [ ]:
random_3d_array.flatten()

array([8, 4, 6, 1, 1, 3, 6, 7, 8, 5, 2, 6, 7, 2, 4, 8, 4, 7, 7, 7, 9, 6,
       6, 3])

In [ ]:
random_3d_array.flatten(order='C')

array([8, 4, 6, 1, 1, 3, 6, 7, 8, 5, 2, 6, 7, 2, 4, 8, 4, 7, 7, 7, 9, 6,
       6, 3])

In [ ]:
random_3d_array.flatten(order='F')

array([8, 7, 1, 4, 8, 9, 4, 2, 3, 7, 5, 6, 6, 4, 6, 7, 2, 6, 1, 8, 7, 7,
       6, 3])

In [ ]:
a = np.array(np.random.randint(10,20,(2,3,4)))
print(a)
print(a.shape)

[[[13 15 17 19]
  [11 18 10 12]
  [12 11 17 13]]

 [[17 13 10 15]
  [18 10 12 12]
  [18 13 11 18]]]
(2, 3, 4)


In [ ]:
np.insert(a,1,100,axis=0)

array([[[ 13,  15,  17,  19],
        [ 11,  18,  10,  12],
        [ 12,  11,  17,  13]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 17,  13,  10,  15],
        [ 18,  10,  12,  12],
        [ 18,  13,  11,  18]]])

In [ ]:
np.insert(a,0,100,axis=1)

array([[[100, 100, 100, 100],
        [ 13,  15,  17,  19],
        [ 11,  18,  10,  12],
        [ 12,  11,  17,  13]],

       [[100, 100, 100, 100],
        [ 17,  13,  10,  15],
        [ 18,  10,  12,  12],
        [ 18,  13,  11,  18]]])

In [ ]:
np.insert(a,0,100,axis=2)

array([[[100,  13,  15,  17,  19],
        [100,  11,  18,  10,  12],
        [100,  12,  11,  17,  13]],

       [[100,  17,  13,  10,  15],
        [100,  18,  10,  12,  12],
        [100,  18,  13,  11,  18]]])

In [ ]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[4 4 5]
  [2 3 5]
  [3 3 4]]

 [[2 4 5]
  [2 4 4]
  [4 2 3]]]
(2, 3, 3)


In [ ]:
np.append(a,55)

array([ 4,  4,  5,  2,  3,  5,  3,  3,  4,  2,  4,  5,  2,  4,  4,  4,  2,
        3, 55])

In [ ]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[4 4 2]]

 [[2 4 5]]]


In [ ]:
np.append(a,b,axis=1)

array([[[4, 4, 5],
        [2, 3, 5],
        [3, 3, 4],
        [4, 4, 2]],

       [[2, 4, 5],
        [2, 4, 4],
        [4, 2, 3],
        [2, 4, 5]]])

In [ ]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[4 3 4]
  [3 2 3]
  [3 3 5]]

 [[5 5 5]
  [3 3 2]
  [2 4 5]]]
(2, 3, 3)


In [ ]:
np.delete(a,(0),axis=0)

array([[[5, 5, 5],
        [3, 3, 2],
        [2, 4, 5]]])

In [ ]:
np.delete(a,(0),axis=1)

array([[[3, 2, 3],
        [3, 3, 5]],

       [[3, 3, 2],
        [2, 4, 5]]])

In [ ]:
np.delete(a,(0),axis=2)

array([[[3, 4],
        [2, 3],
        [3, 5]],

       [[5, 5],
        [3, 2],
        [4, 5]]])

In [ ]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[ 5 18 11]
  [ 4 16 11]
  [17 13  8]]

 [[ 9  7  3]
  [ 6  5 18]
  [15  2  2]]]
(2, 3, 3)


In [ ]:
np.unique(a)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 11, 13, 15, 16, 17, 18])

In [ ]:
a = [1,2,3]
b = a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [ ]:
a = [1,2,3]
b = a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [ ]:
np.arange(3) + 5

array([5, 6, 7])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(0,5,(2,4))
print(b)

[[5 3 3 4]
 [4 5 5 5]]
[[4 3 1 1]
 [1 2 4 2]]


In [ ]:
np.multiply(a,b)

array([[20,  9,  3,  4],
       [ 4, 10, 20, 10]])

In [ ]:
np.divide(a,b)

array([[1.25, 1.  , 3.  , 4.  ],
       [4.  , 2.5 , 1.25, 2.5 ]])

In [ ]:
a=np.random.randint(5,9,(2,4))
print(a)

[[6 8 6 6]
 [7 5 8 5]]


In [ ]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

51
[13 13 14 11]
[26 25]


In [ ]:
print(np.min(a))
print(np.min(a,axis=1))

5
[6 5]


In [ ]:
print(np.sort(a,axis=0))

[[6 5 6 5]
 [7 8 8 6]]


In [ ]:
print(np.sort(a,axis=1))

[[6 6 6 8]
 [5 5 7 8]]
